[package]
name = "goldilocks-ntt"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
homepage = "https://github.com/recmo/goldilocks-ntt"
repository = "https://github.com/recmo/goldilocks-ntt"
description = "A library for fast NTTs over the Goldilocks prime field"
keywords = ["ntt", "goldilocks", "prime", "field"]
categories = ["mathematics"]
readme = "Readme.md"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.151", optional = true }

[dev-dependencies]
criterion = "0.4.0"
proptest = "1.0.0"
rand = "0.8.5"
