[package]
name = "goldilocks-ntt"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
homepage = "https://github.com/recmo/goldilocks-ntt"
repository = "https://github.com/recmo/goldilocks-ntt"
description = "A library for fast NTTs over the Goldilocks prime field"
keywords = ["ntt", "goldilocks", "prime", "field"]
categories = ["mathematics"]
readme = "Readme.md"
license = "MIT"
version = "0.1.0"
edition = "2021"

[features]
default = []
criterion = ["dep:criterion", "rand"]

[[bench]]
name = "criterion"
harness = false
required-features = ["criterion"]

[[bench]]
name = "ntt"
harness = false
required-features = ["rand"]

[dependencies]
serde = { version = "1.0.151", optional = true }
criterion = { version = "0.4.0", optional = true } # For benchmarking only
rand = { version = "0.8.5", optional = true }
rayon = { version = "1.6.1", optional = true }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-flame = "0.2.0"

[dev-dependencies]
proptest = "1.0.0"
